### ISSUE TITLE
Map layers do not draw IE 

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#44]
Using IE version 11.0.9600.17280, map layers do not load on the map (all tools, I believe). The site becomes "laggy" so it almost seems as if something is running in the background maybe??

**Comment by daviswx** [comment]
This should be working now after adding an HTML tag to ensure compatibility compliance.  Here's some more info about how some JavaScript libraries don't get along with different versions of IE:
http://stackoverflow.com/questions/5787245/ie9-javascript-error-script5007-unable-to-get-value-of-the-property-ui-obje

**Comment by hadinon** [comment]
This is bizarre. Mine is still not working even after clearing my cache but I'm not going to reopen this since Corey's and Adrienne's IE versions work. Adrienne is running version 11.

**Comment by hadinon** [comment]
Yeah, I definitely think it's something wrong with my computer because look at how it renders our homepage: 

![image](https://cloud.githubusercontent.com/assets/886682/9769857/a22ebf46-56fa-11e5-8837-d7d486ce2f38.png)
